name: Selenium Test Workflow
on: push
jobs:
        Selenium_Test_Job1:
            name: Selenium Test Job
            runs-on: windows-latest
            steps:
             - run: echo "Thiis running inside a ${{runner.os}} server in GitHub"
             - name: checkout source code
               uses: actions/checkout@v6.0.1
             - run: echo "This repo is ${{ github.repository }} .."
            
    
    
    


